export default [
  {
    title: 'Làng Tôi  Nhà Hát Lớn Hà Nội',
    link: 'https://ticketbox.vn/event/myvillage54042',
    card:
      'https://static.ticketbox.vn/Upload/eventcover/2017/05/30/50CE04.jpg?w=360&maxheight=137&mode=crop&anchor=topcenter',
    coverImg: 'https://ticketbox.vn/event/myvillage54042',
    location: 'Ha Noi',
    category: 'Văn hóa nghệ thuật',
    tablecell: '700.000 VND',
    datemonth: '',
    datenum: '',
    kindOfStage: 'Sân khấu',
    dateday: '',
    datemonth1: 'Tháng 12',
    Headline: '',
    datetime: '',
    locationName: '',
    address: '',
    description: '',
    agency: '',
  },
  {
    title: 'A O Show',
    link: 'https://ticketbox.vn/event/aoshow59795',
    card:
      'https://static.ticketbox.vn/Upload/eventcover/2018/04/09/443DFF.jpg?w=360&maxheight=137&mode=crop&anchor=topcenter',
    coverImg: 'https://ticketbox.vn/event/aoshow59795',
    location: 'Ho Chi Minh',
    category: 'Văn hóa nghệ thuật',
    tablecell: '700.000 VND',
    datemonth: '',
    datenum: '',
    kindOfStage: '',
    dateday: '',
    datemonth1: 'Tháng 12',
    Headline: '',
    datetime: '',
    locationName: '',
    address: '',
    description: '',
    agency: '',
  },
  {
    title: 'Làng Tôi  Nhà Hát Tuồng Việt Nam',
    link: 'https://ticketbox.vn/event/myvillage65304',
    card:
      'https://static.ticketbox.vn/Upload/eventcover/2017/06/23/29B45E.jpg?w=360&maxheight=137&mode=crop&anchor=topcenter',
    coverImg: 'https://ticketbox.vn/event/myvillage65304',
    location: 'Ha Noi',
    category: 'Văn hóa nghệ thuật',
    tablecell: '700.000 VND',
    datemonth: '',
    datenum: '',
    kindOfStage: 'Sân khấu',
    dateday: '',
    datemonth1: 'Tháng 12',
    Headline: 'Làng Tôi  Nhà Hát Tuồng Việt Nam',
    datetime:
      'Thứ 6, 20 Tháng 12 2019 (06:00 PM  07:30 PM)\n                                            \n                                            \n                                              + 5 ngày khác',
    locationName: 'Vietnam Tuong Theatre',
    address: '51A Đường Thành, Quận Hoàn Kiếm, Thành Phố Hà Nội',
    description:
      'GIỚI THIỆU LÀNG TÔI\n\nLà sản phẩm sáng tạo đầu tiên của nhóm tác giả Tuấn Lê  Nguyễn Lân – Nhất Lý – Tấn Lộc, cũng là nhóm tác giả của À Ố Show. Làng Tôi đã biểu diễn hơn 300 suất tại nhiều nước trên thế giới từ 2009 đến 2012: Hà Lan, Pháp, Bỉ, Đức, Tây Ban Nha, Hy Lạp, Thụy Sĩ, Hong Kong.\n\n \n\nLàng Tôi là một bức tranh làng quê Bắc Bộ bình yên, khi ngày mới bắt đầu với tiếng gà gáy sáng, những đứa trẻ chơi đũa tre trong lúc cha mẹ làm việc ngoài đồng ruộng. Nơi những người nông dân hút thuốc lào với chiếc điếu cày bằng tre, lúc nghỉ giải lao dưới bóng cây giữa nắng trưa hè gay gắt. Nơi tối đến, những cặp tình nhân tình tự trên những cây cầu tre dưới ánh sáng của hàng ngàn vì sao.\n\nVới kỹ thuật xiếc mới, tre chính là linh hồn của vở diễn, là người dẫn dắt câu chuyện, xây dựng và thay đổi các khung cảnh, kết nối hai mươi nghệ sĩ xiếc và nhạc công Hà Nội trong sắc màu âm thanh của các nhạc cụ truyền thống.\n\n \n\n \n\nMY VILLAGE VERSION AT A GLANCE\n\n \n\nMy Village is a delicate merge of tradition and innovation, where poetic beauty of Northern Vietnam’s village life is presented under new cirque approach.\n\nFarming, building activities, traditional games, lifestyle of Northern villagers are recreated by ancestral bamboo props, breathtaking cirque and rhythmic dance, juggling, and acrobatic movements to distinct folk music played from more than 20 musical instruments.\n\n \n\nThe show was created in 2005 in Hanoi, by the same creators of À Ố Show. My Village toured around the world from 2009 to 2012, with over 300 shows in France, Holland, Spain, Belgium, Greece, Switzerland, Germany, Hong Kong.\n\n \n\n\nA BLEND OF\nBamboo Cirque\nAcrobatics\nContemporary Dance\nChoreography\n\n\nMUSIC\nLive\n17 Vietnamese musical instruments.\n\n\nDURATION\nApproximately 60 minutes\n\n \n\n** All the seats are on a "best available" basis. If you made online payment ,we will contact you to arrange the seats. If you choose COD, we will choose the best available seats for you. If you buy two or more tickets, we\'ll make sure that you all sit together.\n\n \n\n\n\tEticket holder must arrive 45 minutes before show time in order to exchange eticket for Theater Pass.\n\tTheater doors will be closed 15 minutes before show time.\n\n\n \n\nNẾU QUÝ KHÁCH MUỐN ĐẶT NHIỀU VÉ HƠN SO VỚI SỐ LƯỢNG CÓ SẴN TRÊN HỆ THỐNG, HOẶC ĐẶT SAU 9H30 SÁNG NGÀY CÓ SUẤT DIỄN, XIN VUI LÒNG LIÊN HỆ HOTLINE CỦA TICKETBOX.\n\n \n\nPLEASE CONTACT US IF YOU NEED MORE TICKETS OR BOOK TICKETS AFTER 09:30AM (ON SHOW DAY).\n\n',
    agency: 'Lune Production',
  },
  {
    title: 'Tường leo núi Vertical Adventures | DaLat SufferFest™ 2020',
    link:
      'https://ticketbox.vn/event/dalatsufferfest2020verticaladventures76257',
    card:
      'https://static.ticketbox.vn/Upload/eventcover/2019/07/09/E40AE2.jpg?w=360&maxheight=137&mode=crop&anchor=topcenter',
    coverImg:
      'https://ticketbox.vn/event/dalatsufferfest2020verticaladventures76257',
    location: 'Lam Dong',
    category: 'Thể thao',
    tablecell: '125.000 VND',
    datemonth: '',
    datenum: '',
    kindOfStage: 'Ngoài trời',
    dateday: '',
    datemonth1: 'Tháng 2',
    Headline: 'Tường leo núi Vertical Adventures | DaLat SufferFest™ 2020',
    datetime:
      'Thứ 6, 28 Tháng 2 2020  Chủ nhật, 01 Tháng 3 2020 (08:00 AM  06:00 PM) \n                                            \n                                            \n                                              + 1 ngày khác',
    locationName: 'Cầu Đất Farm',
    address:
      'Truong Tho Village, Tram Hanh Commune, Da Lat City, Lam Dong Province., Thành Phố Đà Lạt, Tỉnh Lâm Đồng',
    description:
      "Vertical Adventures: Climbing & Aerial Games\n\n\tChinh phục môn thể thao leo núi ngoài trời và các hoạt động mạo hiểm từ trên cao. Tường leo núi Vertical sẽ đem lại những niềm vui và trải nghiệm bất tận, mới lạ với người tham gia. Tường được đặt tại đồi chè nổi tiếng Cầu Đất Farm và mở cửa bán vé xuyên suốt cuối tuần cho người tham gia tự do, đối với các Vận Động Viên thi đấu cần phải đăng ký trước để được đặt chỗ.\n\n\tPursuing the joy of Rock Climbing and High Angle thrills one move at a time. Vertical is all about fun and invaluable life experiences. Hosted at Cau Dat Farm and open to walkins throughout the weekend, Vertical Adventures promises a climbing and aerial experience found nowhere else. \n\n\t\n\n\t\n\n\t\n\n\t   \n\n\tDa Lat  SufferFest™  Tuyen Lam Lake: Swallow the Beast, Savor the Beauty\n\n\tSufferFest is a mass participatory multisports events festival. Every event is individually organized and recognized with awards and achievements. Register for any one (1) individual event or register for multiple events held throughout the weekend.  SufferFest is home to some of Vietnam's most unique sports experiences in one of Vietnam's most desirable locations.\n\n\tSufferFest là một sự kiện thể thao cao cấp hội tụ nhiều loại hình thi đấu khác nhau hấp dẫn nhất Việt Nam. Mỗi cuộc thi của SufferFest đều được tổ chức và công nhận độc lập với những giá trị giải thưởng khác nhau.  Bạn có thể đăng ký một (1) hoặc nhiều cuộc đua trong suốt tuần lễ SufferFest™, nơi mà đem đến cho bạn những trải nghiệm thể thao độc nhất vô nhị tại địa điểm thiên nhiên lý tưởng ở Việt Nam\n\n\t \n\n\t\n\n\tA Positive Future Project: Awareness  Understanding  Action\n\n\tDự án 'A Positive Future Project' là nhiệm vụ quan trọng nhất mà SufferFest mong muốn thực hiện được. Mục đích của dự án là truyền tải và tương tác các kiến thức sâu rộng về ngôi nhà chung của chúng ta  mẹ Thiên Nhiên, mẹ Trái Đất; cũng như là nơi trình bày những ý tưởng , dự án về môi trường, bảo tồn thiên nhiên, v.v.. từ sự nỗ lực của nhiều đơn vị, câu lạc bộ khác nhau; những người luôn có nhiệt huyết trong việc cố gắng cải thiện sức chứa và duy trì sự sống bền vững trên Trái Đất. Dự án này hy vọng có thể lan toả các thông điệp, học hỏi và phát triển khả năng hiểu biết về tầm quan trọng của duy trì sự sống bền vững trên Trái Đất, từ đó mọi người có thể bắt tay vào việc phát triển ý tưởng và ứng dụng nó vào công nghệ thông tin, triết lý kinh doanh, cuộc sống hằng ngày. \n\n\tA Positive Future Project is the priority mission of SufferFest.  The goal is to engage in a deeper knowledge of the state of our home planet Earth and to showcase the efforts of as many groups and projects as possible who are actively dedicating their energy to critical transitional efforts to improve the carrying capacity and sustainability of all life on Earth.  The Project's intentions is to learn, spread awareness, understand possibilities and take action through innovation and transformational technology and business practices. \n\n\t \n\n\tTimeline:\n\n\t\n\n\t \n\n\tSize áo / Tshirt Size Chart:",
    agency: 'BOZO Ventures',
  },
  {
    title: 'MultiTerrain Running | DaLat SufferFest™ 2020',
    link:
      'https://ticketbox.vn/event/dalatsufferfestseason2multiterrainrun76263',
    card:
      'https://static.ticketbox.vn/Upload/eventcover/2019/07/10/4DD861.jpg?w=360&maxheight=137&mode=crop&anchor=topcenter',
    coverImg:
      'https://ticketbox.vn/event/dalatsufferfestseason2multiterrainrun76263',
    location: 'Lam Dong',
    category: 'Thể thao',
    tablecell: '250.000 VND',
    datemonth: '',
    datenum: '',
    kindOfStage: 'Ngoài trời',
    dateday: '',
    datemonth1: 'Tháng 2',
    Headline: 'MultiTerrain Running | DaLat SufferFest™ 2020',
    datetime:
      'Thứ 6, 28 Tháng 2 2020 (03:30 PM  05:30 PM)\n                                            \n                                            \n                                              + 3 ngày khác',
    locationName: 'Hồ Tuyền Lâm / Tuyen Lam Lake',
    address: 'Hồ Tuyền Lâm / Tuyen Lam Lake, Thành Phố Đà Lạt, Tỉnh Lâm Đồng',
    description:
      "Thời gian bắt đầu: \n\n+ 5Km:\n\nNgày: Thứ sáu, 28/02/2020 \n\nGiờ: 15:00  17:30\n\n+ 16Km/ 21Km/ 42Km:\n\nNgày: Chủ nhật, 01/03/2020\n\nGiờ: 8:00  16:00\n\n \n\nMultiTerrain Run: Experience the Flow\n\nMultiTerrain là cuộc đua chạy bộ đáng giá bắt buộc phải tham gia nếu bạn là một dân chạy thực thụ; cuộc đua được phát triển và xây dựng với các tiêu chí cao nhất cùng với sự khám phá thiên nhiên núi rừng đa dạng trên các cung đường chạy. Các cự ly hứa hẹn sẽ đem đến những trải nghiệm khó quên mà người tham gia sẽ không bao giờ nghĩ tới. Đối với các cự  ly MultiTerrain, mỗi chặng đua sẽ là một niềm tự hào riêng. \n\nMultiTerrain events are premium race routes developed with high expectation and scrutinizing exploration. The routes are designed to journey participants through an experience beyond their expectations.  For MultiTerrain races, the race route is the pride of the product. \n\nCự ly 42km  1/3/2020  8AM to 4PM\n\nCự ly 42km  full marathon sẽ lưu lại những hình ảnh độc đáo trộn lẫn giữa kiến trúc nhân tạo và  vẻ đẹp thuần hoá của thiên nhiên mà Vận Động Viên sẽ đi qua, từ những ngôi nhà làm bằng tre nứa đến những công trình 5 sao hoà lẫn vào thiên nhiên Đà Lạt. Hy vọng khi đến vạch về đích, Vận Động VIên sẽ có được cảm giác nhẹ nhõm và muốn chặng đua luôn mãi tiếp tục \n\nA full marathon distance capturing a mesmerizing mixture of human architecture and natural environments, ranging from bamboo ecohomestays to indigenous landscapes and multiple 5 Star properties. The finish line hopes to offer an intense feeling of relief as well as a hunger for more. \n\n\n\nCự ly 21Km  1/3/2020  9AM to 4PM\n\nMột cung đường half marathon quý giá. Đây là cự ly phổ biến nhất, kết hợp giữa thiên nhiên hoang dã và những cảnh đẹp khó tả sẽ xuất hiện trên cung đường chạy có một không hai này. Điều này sẽ luôn thu hút những runners đam mê thiên nhiên quay lại từ năm này qua năm khác. \n\nA half marathon treasure. This most popular running distance intertwines in nature and spreads over breathtaking scenery for a oneofakind course that runners are sure to return for year over year.\n\n\n\nCự ly 16Km  1/3/2020  9AM to 4PM\n\nĐược thiết kế dành cho những người mới bắt đầu chạy, chưa thoải mái với cự ly 21km hoặc cho những người đang tìm kiếm hoạt động nhẹ nhàng cùng với thiên nhiên ngoài trời, hoạt động cùng nhóm bạn, đồng nghiệp. Với cự ly 16km mới lại này sẽ bắt đầu từ SAM Resort Tuyen Lam, theo con đường nhựa trải dọc các suờn núi, quanh sân golf của SwissbelResort và những cánh đồng cà phê của người dân tộc sẽ đem đến cho bạn những bức ảnh, cảnh đẹp về thiên nhiên trên cung đường chạy đặc biệt này; cự ly sẽ kết thúc ở một trong những resort thơ mộng nhất ở Hồ Tuyền Lâm  Edensee Resort\n\nDesigned as a stepping stone for those not yet comfortable in taking the step to a halfmarathon or for those looking for a casual, comfortable day out. This uncommon course distance starts from SAM Resort Tuyen Lam, follows the mountain roads around the SwissbelResort golf course and ethnic coffee plantations with consistent photo worthy scenery and finishes at the romantic Edensee Tuyen Lam Resort. \n\n\n\nCự ly 5Km dành cho gây quỹ chương trình The Innovation Initiative  28/2/2020  3:30PM to 5:30PM\n\nToàn bộ 100% doanh thu của cự ly này sẽ được gây quỹ xuyên suốt cho các hoạt động môi trường, thiên nhiên cùng với các báo cáo công khai cho từng hoạt động trong quá trình thực hiện. Cự ly này tạo động lực cho mọi người, ai cũng có thể tham gia từ trẻ nhỏ đến người lớn tuổi. Đường chạy này là một dịp đặc biệt cho gia đình, bạn bè cũng khởi động, lấy tinh thần  gắn kết cùng nhau bắt đầu cho tuần lễ SufferFest\n\n100% of the event sales revenues will be donated to the Innovation Initiative along with full public disclosure and open source access to project progress. A route introduced to encourage everyone and anyone to take part in the movement. A fun and enjoyable race route. Take your time or use it as a warm up to your next event.  \n\n\n\nDaLat  SufferFest™  Tuyen Lam Lake: Swallow the Beast, Savor the Beauty\n\nSufferFest is a mass participatory multisports events festival. Every event is individually organized and recognized with awards and achievements. Register for any one (1) individual event or register for multiple events held throughout the weekend.  SufferFest is home to some of Vietnam's most unique sports experiences in one of Vietnam's most desirable locations.\n\nSufferFest là một sự kiện thể thao cao cấp hội tụ nhiều loại hình thi đấu khác nhau hấp dẫn nhất Việt Nam. Mỗi cuộc thi của SufferFest đều được tổ chức và công nhận độc lập với những giá trị giải thưởng khác nhau.  Bạn có thể đăng ký một (1) hoặc nhiều cuộc đua trong suốt tuần lễ SufferFest™, nơi mà đem đến cho bạn những trải nghiệm thể thao độc nhất vô nhị tại địa điểm thiên nhiên lý tưởng ở Việt Nam\n\n\n\nA Positive Future Project: Awareness  Understanding  Action\n\nDự án 'A Positive Future Project' là nhiệm vụ quan trọng nhất mà SufferFest mong muốn thực hiện được. Mục đích của dự án là truyền tải và tương tác các kiến thức sâu rộng về ngôi nhà chung của chúng ta  mẹ Thiên Nhiên, mẹ Trái Đất; cũng như là nơi trình bày những ý tưởng , dự án về môi trường, bảo tồn thiên nhiên, v.v.. từ sự nỗ lực của nhiều đơn vị, câu lạc bộ khác nhau; những người luôn có nhiệt huyết trong việc cố gắng cải thiện sức chứa và duy trì sự sống bền vững trên Trái Đất. Dự án này hy vọng có thể lan toả các thông điệp, học hỏi và phát triển khả năng hiểu biết về tầm quan trọng của duy trì sự sống bền vững trên Trái Đất, từ đó mọi người có thể bắt tay vào việc phát triển ý tưởng và ứng dụng nó vào công nghệ thông tin, triết lý kinh doanh, cuộc sống hằng ngày. \n\nA Positive Future Project is the priority mission of SufferFest.  The goal is to engage in a deeper knowledge of the state of our home planet Earth and to showcase the efforts of as many groups and projects as possible who are actively dedicating their energy to critical transitional efforts to improve the carrying capacity and sustainability of all life on Earth.  The Project's intentions is to learn, spread awareness, understand possibilities and take action through innovation and transformational technology and business practices. \n\nTimeline:\n\n \n\n    Thông tin vé: \n\n\n\nSize áo / Tshirt Size Chart:",
    agency: 'Bozo Ventures',
  },
  {
    title: 'TEMPT',
    link: 'https://ticketbox.vn/event/tempt77028',
    card:
      'https://static.ticketbox.vn/Upload/eventcover/2019/09/19/E84534.jpg?w=360&maxheight=137&mode=crop&anchor=topcenter',
    coverImg: 'https://ticketbox.vn/event/tempt77028',
    location: 'Ho Chi Minh',
    category: 'Nhạc sống',
    tablecell: '1.500.000 VND',
    datemonth: 'Tháng 12',
    datenum: '22',
    kindOfStage: 'Vui chơi giải trí',
    dateday: 'Chủ nhật',
    datemonth1: '',
    Headline: 'TEMPT',
    datetime: 'Chủ nhật, 22 Tháng 12 2019 (05:00 PM  09:00 PM)',
    locationName: 'Nhà hát VOH Music One',
    address: '37 Nguyễn Bỉnh Khiêm, Quận 1, Thành Phố Hồ Chí Minh',
    description:
      'FAN MEETING\n\tNgày/ Date: 22.12.2019 \n\t• Thời gian/ Time: 17:00\n\t• Địa điểm/ Venue: VOH – Music One\n\t• Địa chỉ/ Address: 37 Nguyen Binh Khiem, Da Kao Ward, District 1\n\n\tPRIVATE DINNER PARTY: (LOVE zone only)\n\tNgày/ Date: 21.12.2019 \n\t• Thời gian/ Time: 18:00\n\t• Địa điểm/ Venue: Opus Sài Gòn\n\t• Địa chỉ/ Address: 12 Phan Ke Binh, Da Kao Ward, District 1, HCMC\n\n\tThời gian bắt đầu bán vé/ Ticket selling time: 10.00AM – 6/10/2019 \n\tKênh phân phối vé/ Ticket Online Booking: Ticketbox.vn\n\n\tKênh thông tin chính thức / Fan Meeting Offical FanPage:\n\t Facebook: @gemeventmedia\n\t Twitter: @GEMEventMedia\n\tNhà sản xuất/ Producer: \n\tVOH Music One – Opera House\n\n\tĐơn vị truyền thông/Media: \n\n\tTwins Media, Chuyện Fan Girl',
    agency: 'G.E.M Event Media',
  },
  {
    title: 'Vở Múa: ĐA THỨC | METHOD: Dance Theater',
    link:
      'https://ticketbox.vn/event/methodcontemporaryperformancebyh2qart77371',
    card:
      'https://static.ticketbox.vn/Upload/eventcover/2019/12/07/0ECB34.jpg?w=360&maxheight=137&mode=crop&anchor=topcenter',
    coverImg:
      'https://ticketbox.vn/event/methodcontemporaryperformancebyh2qart77371',
    location: 'Ho Chi Minh',
    category: 'Văn hóa nghệ thuật',
    tablecell: '150.000 VND',
    datemonth: '',
    datenum: '',
    kindOfStage: 'Sân khấu',
    dateday: '',
    datemonth1: 'Tháng 12',
    Headline: 'Vở Múa: ĐA THỨC | METHOD: Dance Theater',
    datetime:
      'Thứ 6, 20 Tháng 12 2019 (08:00 PM  10:00 PM)\n                                            \n                                            \n                                              + 1 ngày khác',
    locationName: 'Nhà hát Quân đội',
    address: '140 Cộng Hòa, Phường 4, Quận Tân Bình, Thành Phố Hồ Chí Minh',
    description:
      "(𝑬𝒏𝒈𝒍𝒊𝒔𝒉 𝒃𝒆𝒍𝒐𝒘)\n\nSử dụng hai cây gậy dài 5m và 6 hòn đá nặng xấp xỉ cơ thể người, các diễn viên nổi tiếng đến từ những nền tảng chuyển động khác nhau (Balê, HipHop, Đương Đại, Trình diễn) sẽ đồng bộ hóa chuyển động của mình như thế nào trong vở múa ĐA THỨC?\n\nDưới bàn tay của biên đạo múa người New Zealand  Ross McCormack, trên nền nhạc điện tử mang âm hưởng Tây Nguyện được nhạc sĩ Jason Wright sáng tác dành riêng cho vở, các nghệ sĩ Nguyễn Duy Thành, Vũ Ngọc Khải, Lâm Duy Phương, Lâm Tố Như, Nguyễn Thạch Sang, Nguyễn Quang Tư sẽ sử dụng toàn bộ cơ thể của mình để giao tiếp, và bộc lộ vô số trạng thái cảm xúc khác nhau. \n\nĐi coi múa không chỉ là đi coi chuyển động, mà là coi khả năng biểu đạt kì lạ của cơ thể người!\n\nTham gia chương trình ưu đãi MUA 1 TẶNG 1 khi mua vé xem vở tại đây: http://bit.ly/2RY0Joe\n\nCám ơn sự hỗ trợ hào phóng của ADORA DANCE GROUP và YVU (Phục trang)\n\nĐối tác truyền thông: Hanoi Grapevine, Cổ Động, Saigoneer, Yêu Múa, Đài Phát Thanh..\n\n►►THÔNG TIN VỞ DIỄN:\nThời gian: 20:00  22:00 ngày 20 và 21 tháng 12 năm 2019.\nĐịa điểm: Nhà hát Quân Đội khu vực phía Nam  140 Cộng Hòa, Phường 15, Tân Bình, Hồ Chí Minh.\n🔥 Xem thêm thông tin về vở diễn tại đây: https://www.facebook.com/events/579406656130928/\n_____________________________________________\nEach dancer has their own methodology of movement. Together, they create one kind of method!\n \n\nWorking with 5m long poles and 6 heavy rocks, how would 6 talented dancers coming from different backgrounds (Ballet, HipHop, Contemporary Dance, Performance Art) synchronize their movements in METHOD: Dance Theater?\n\nUnder the wild choreography style of Ross McCormack  coming all the way from New Zealand, surrounded by electronic soundscape in combination with Vietnam Central Highland music composed by Jason Wright, ourr artists Nguyễn Duy Thành, Vũ Ngọc Khải, Lâm Duy Phương, Lâm Tố Như, Nguyễn Thạch Sang, Nguyễn Quang Tư will use their whole body to communicate and express!\n\nGoing to a dance show is not only all about watching the movements, but also seeing the miracle ability of human body's expression!\n\nRegister for our BUY 1 GET 1 promotion here:  http://bit.ly/2RY0Joe\n\nThanks to our generous supporters: ADORA DANCE GROUP and YVU (Costume).\n\nMedia Partners: Hanoi Grapevine, Cổ Động, Saigoneer, Yêu Múa, Đài Phát Thanh..\n\n►►𝐄𝐕𝐄𝐍𝐓 𝐃𝐄𝐓𝐀𝐈𝐋𝐒:\nTime: 20:00  22:00 December 20 & 21, 2019.\nLocation: The Army Theater 140 Cong Hoa, Ward 15, Tan Binh, Ho Chi Minh City, Vietnam.\n🔥Visit our event link: https://www.facebook.com/events/579406656130928/",
    agency: 'H2Q ART CO',
  },
  {
    title: 'SkyXX Garden & Lounge',
    link: 'https://ticketbox.vn/event/skyxxpackage77523',
    card:
      'https://static.ticketbox.vn/Upload/eventcover/2019/10/23/349C69.jpg?w=360&maxheight=137&mode=crop&anchor=topcenter',
    coverImg: 'https://ticketbox.vn/event/skyxxpackage77523',
    location: 'Ho Chi Minh',
    category: 'Nightlife',
    tablecell: '7.300.000 VND',
    datemonth: '',
    datenum: '',
    kindOfStage: '',
    dateday: '',
    datemonth1: 'Tháng 12',
    Headline: '',
    datetime: '',
    locationName: '',
    address: '',
    description: '',
    agency: '',
  },
  {
    title: 'Liquid Buffet',
    link: 'https://ticketbox.vn/event/liquidbuffet77654',
    card:
      'https://static.ticketbox.vn/Upload/eventcover/2019/11/29/265A94.jpg?w=360&maxheight=137&mode=crop&anchor=topcenter',
    coverImg: 'https://ticketbox.vn/event/liquidbuffet77654',
    location: 'Ho Chi Minh',
    category: 'Nightlife',
    tablecell: '699.000 VND',
    datemonth: 'Tháng 12',
    datenum: '24',
    kindOfStage: '',
    dateday: 'Thứ 3',
    datemonth1: '',
    Headline: 'Liquid Buffet',
    datetime:
      'Thứ 3, 24 Tháng 12 2019  Thứ 3, 31 Tháng 12 2019 (06:00 PM  11:45 PM)',
    locationName: 'Sảnh Gosset Rooftop  Capella Gallery Hall',
    address: '24 Đường 3/2, Quận 10, Thành Phố Hồ Chí Minh',
    description:
      'LIQUID BUFFET: JUST BEER IT!\n\n“Rung rinh” đêm Giáng Sinh cùng Liquid Buffet!\n\n[English below]\n\nGiáng Sinh này bạn đã có kế hoạch cho riêng mình hay bạn đang tìm một nơi để “rung rinh” cùng hội bạn thân và đồng nghiệp?!\n\n\n\nCòn gì tuyệt vời hơn khi được đắm mình vào không gian rooftop độc đáo, vừa được ngắm nhìn khung cảnh Sài Gòn nhộn nhịp tráng lệ đêm Giáng Sinh, vừa được thưởng thức “không giới hạn” hương vị mới lạ tươi mát đến từ những dòng bia thủ công danh tiếng, nhâm nhi cùng những món ăn đặc trưng của đêm Giáng Sinh như: Gà tây nhồi hạt dẻ, thăn bò Úc nướng Texas, sườn heo đút lò,....Hòa quyện cùng những giai điệu tươi vui sôi động đến từ ban nhạc acoustic, chắc chắn sẽ khiến bạn phải lắc lư không ngừng và có một trải nghiệm đáng nhớ đêm Giáng Sinh đấy!\n\nCÓ GÌ TẠI LIQUID BUFFET: JUST BEER IT !?\n\n\n\t\n\tThưởng thức bia không giới hạn với hơn 09 hương vị độc đáo và đặc trưng nhất, đến từ thương hiệu bia thủ công danh tiếng Pasteur Street Brewing  và Heart of Darkness cùng các dòng bia Heineken, Tiger và Budweiser.\n\t\n\t\n\tNhấn nhá với ẩm thực Á – Âu tiếp năng lượng cho buổi gặp gỡ.\n\t\n\t\n\tGóc Beer Games để bạn khuấy động cuộc vui.\n\t\n\t\n\tChill trong không gian mở của thành phố về đêm tại The Gosset rooftop.\n\t\n\t\n\tĐắm chìm trong giai điệu Acoustic rất Tây\n\t\n\n\n\n\nBia thủ công với nhiều hương vị thơm ngon, độc đáo từ thương hiệu Pasteur Street và Heart Of Darkness\n\n\n\nKhuấy động không khí với âm nhạc \n\n\n\nChill không gian với toàn cảnh thành phố Sài Gòn trong đêm Giáng Sinh\n\n\n\nĐẶT VÉ NGAY ĐỂ UỐNG BIA KHÔNG GIỚI HẠN TẠI LIQUID BUFFET!\n\n\n\nShake up your Christmas with Liquid Buffet!\n\nAre you ready to shake your body up with your buddies on Christmas night?!\n\nWhat is more wonderful than being immersed in the unique rooftop space, just watching the magnificent Saigon scenery, and enjoying the "unlimited" fresh flavors from the famous craft beer brands, sipping with typical dishes of Christmas night such as: Roast turkey with chestnut stuffing, grilled Australian pork tenderloin, baked pork ribs, .... Blended with cheerful tunes of the acoustic band, will definitely make you sway nonstop and have a memorable Christmas night experience!\n\n\n\t\n\tChill in unlimited 09 types of beers, from the famous Pasteur Street Craft Beer Brewing and the one and only Heart Of Darkness; together with Heineken/Budweiser/Tiger\n\t\n\t\n\tEnjoy Western – Asian cuisine to extra boost energy\n\t\n\t\n\tBeer Games corner for your playful time\n\t\n\t\n\tExperience the openedspace for “highviewing” the urban city\n\t\n\t\n\tDeeping in Acoustic music for your wonderful time\n\t\n\n\n​\n\nPlayful space at The Gosset Rooftop\n\n\n\n \n\n\n\n... to enjoy craft beer.\n\nJOIN US AND BOOK TICKET RIGHT NOW!',
    agency: 'Capella Gallery Hall',
  },
  {
    title: 'Lễ hội âm nhạc truyền thống Việt  Viet traditional music festival',
    link:
      'https://ticketbox.vn/event/lehoiamnhactruyenthongvietviettraditionalmusicfestival77835',
    card:
      'https://static.ticketbox.vn/Upload/eventcover/2019/12/03/EF748F.jpg?w=360&maxheight=137&mode=crop&anchor=topcenter',
    coverImg:
      'https://ticketbox.vn/event/lehoiamnhactruyenthongvietviettraditionalmusicfestival77835',
    location: 'Kien Giang',
    category: 'Nhạc sống',
    tablecell: '150.000 VND',
    datemonth: 'Tháng 12',
    datenum: '24',
    kindOfStage: '',
    dateday: 'Thứ 3',
    datemonth1: '',
    Headline:
      'Lễ hội âm nhạc truyền thống Việt  Viet traditional music festival',
    datetime:
      'Thứ 3, 24 Tháng 12 2019  Thứ 3, 31 Tháng 12 2019 (04:00 PM  10:00 PM)',
    locationName: 'Phố đi bộ Sonasea Resort & Villas',
    address: 'Dương Tơ, Phú Quốc, Huyện An Biên, Tỉnh Kiên Giang',
    description:
      '“Lễ hội âm nhạc truyền thống Việt Nam” tại Đảo Ngọc Phú Quốc từ ngày 24/12/2019 – 03/01/2020 tại  Phố đi bộ Sonasea Phú Quốc, thuộc Khu tổ hợp du lịch Sonasea Villas & Resort. Chương trình nhằm mục tiêu tôn vinh các giá trị tinh thần của người Việt, giới thiệu những nét độc đáo và đặc sắc trong văn hóa truyền thống đến các Du khách trong và ngoài nước bằng câu chuyện truyền thuyết được kể lại thông qua giai điệu âm nhạc mang đậm bản sắc và văn hóa truyền thống Việt Nam. \n\n\tChương trình bao gồm các hoạt động:\n\n\t+ Không gian trưng bày các sản phẩm văn hóa truyền thống Việt Nam: Nhạc cụ, Nón lá, Áo Dài, Sản phẩm lưu niệm \n\n\t+ Khu trò chơi dành cho du khách với các trò chơi dân gian Việt Nam: Ô ăn quan, nhảy sạp, nặn tò he, vẽ tranh, ghép tranh\n\n\t+ Chương trình ca múa nhạc truyền thống \n\n\t+ Chương trình giao lưu giữa Nghệ sĩ và khán giả ..',
    agency: 'CÔNG TY CỔ PHẦN TRUYỀN THÔNG & TỔ CHỨC SỰ KIỆN GTO PHÚ QUỐC',
  },
  {
    title: 'TeTucation and Year End Party @ Salon Saigon',
    link:
      'https://ticketbox.vn/event/tetucationandyearendpartysalonsaigon77921',
    card:
      'https://static.ticketbox.vn/Upload/eventcover/2019/12/06/61E1F4.jpg?w=360&maxheight=137&mode=crop&anchor=topcenter',
    coverImg:
      'https://ticketbox.vn/event/tetucationandyearendpartysalonsaigon77921',
    location: 'Ho Chi Minh',
    category: 'Hội họp',
    tablecell: '250.000 VND',
    datemonth: 'Tháng 12',
    datenum: '22',
    kindOfStage: 'Văn hóa nghệ thuật',
    dateday: 'Chủ nhật',
    datemonth1: '',
    Headline: 'TeTucation and Year End Party @ Salon Saigon',
    datetime: 'Chủ nhật, 22 Tháng 12 2019 (05:30 PM  08:00 PM)',
    locationName: 'Salon Saigon',
    address: '6D Ngo Thoi Nhiem, Quận 3, Thành Phố Hồ Chí Minh',
    description:
      '** PLEASE SCROLL DOWN FOR ENGLISH**\n\n\t \n\n\tChương trình: "NÓI VỀ TẾT MIỀN NAM" và Tiệc Cuối Năm tại Salon Saigon\n\n\t \n\n\tThời gian: Chủ Nhật ngày 22 tháng 12 năm 2019 từ 17h30\n\tNgôn ngữ: Tiếng Việt và phiên dịch Tiếng Anh\n\n\tChương trình:  17h3018h00: Đón tiếp khách quý\n\n\t                        18h0020h00: Bắt đầu chương trình \n\n\t \n\n\tSalon Saigon và nhóm Đại Nam Hội Quán trân trọng giới thiệu chương trình: “Nói về tết Miền Nam” với mong muốn gởi đến những bạn trẻ những câu chuyện về ngày tết xưa, nhứt là những bạn trên chốn thị thiềng có thể mà hình dung một bầu không khí ấm cúng của những gia đình người Việt. Một sự chuẩn bị hằng tháng trời để giành cho một ngày tết thiệt trọn vẹn, xin được gói lại trong hơn một tiếng đồng hồ bằng những cuộc nói chuyện thân tình, ly trà ngào ngạt hương thơm theo làn khói, miếng mứt, miếng trầu; để mà kể chuyện nghe chơi. \n\n\tSự khác biệt của Tết ở Miền Nam so với những nơi khác và nhứt là sự biến chuyển từ một cái Tết Truyền thống sang một cái Tết hiện đại như ngày nay như thế nào, sự mất dần của chùm pháo, dĩa ngũ quả xưa,…. Chúng tui mong muốn sẽ giải thích phần nào sự khúc mắc của những bạn muốn hiểu hơn về văn hóa, phong tục xưa.\n\n\tChương trình sẽ được tổ chức trong khuôn khổ một bữa tiệc ấm cúng nhân dịp kết thúc một năm cùng trải qua những sự kiện tại Salon Saigon – 6D Ngô Thời Nhiệm, Q3. Tại đây, chúng ta không chỉ cùng nhau nhìn lại một năm đã qua, cùng là dịp trao đổi, gặp gỡ các học giả, sử gia đã từng hợp tác với Salon Saigon mà còn là lúc chúng ta cùng nhau “đón giao thừa” sớm và tìm hiểu phong tục, tập quán của ông cha ta, kế thừa quá khứ, lịch sử và cùng nhau kiến tạo tương lai.\n\n\tVề nhóm ĐạiNamHộiQuán\n\n\tĐược thành lập vào ngày Mồng 8 tháng Giêng năm Đinh dậu [17 tháng 2 năm 2017], cho đến nay ĐạiNam HộiQuán đã có 14 thành viên. Đây là nơi tập trung lại với nhau bằng niềm mong muốn học hỏi và trau dồi thêm vốn kiến thức về các giá trị xưa, văn hóa của Miền Nam nói riêng và Việt Nam nói chung. Những giá trị văn hóa xưa dần bị lãng quên và sai lệch đi, đó là niềm thôi thúc các thành viên thành lập nên nhóm ĐạiNam HộiQuán.\n\n\tTrong năm 2019 này, nhóm có hàng loạt những chuỗi dự án, chương trình xuyên suốt như giới thiệu về Đám cưới xưa, kể chuyện Áo dài, kể chuyện xưa nghe chơi, đờn ca hồi đó,… và sắp tới đây, nhơn dịp cuối năm Kỷ Hợi, ĐạiNamHộiQuán thực hiện một chương trình nhằm đánh dấu quá trình hoạt động trong năm nay của Hội quán, với mục tiêu là giới thiệu về cái Tết xưa ở Miền Nam và sự khác biệt với hiện nay, thứ nhì là muốn liên kết những bạn yêu văn hóa cùng chung có nơi gặp mặt, sanh hoạt, cùng nhau chia sẻ những câu chuyện xưa, những bài học quí báu…\n\n\t/////////////////////\n\n\t"Talk about Tet in Southern Vietnam and Year End Party @ Salon Saigon\n\n\tTime: Sunday, December 22nd, 2019 from 5.30pm\n\n\tLanguage: Vietnamese with English translation\n\n\tProgram:  5.30pm  6.00pm: Welcoming Guests\n\n\t                 6.00pm  8.00pm: Performance\n\n\tSalon Saigon and ĐạiNamHộiQuán Group are delighted to introduce “Talk about Tet in Southern Vietnam” in which we\'d love to send the stories of the old Tet to our youths, especially those of the city, so that we can all feel the cozy atmosphere of a Vietnamese family. Our months of preparation would like to consolidate into one hour and perhaps more for us all to enjoy a wellgrounded Tet, with small talks, aromatic teas, jams, and storytelling. We will discuss the difference between the Southern Tet and that of other areas, the transformation of a traditional Tet to a modern one, and the slow disappearance of the firecrackers, the tray of the five fruits, and more... We would like to share somehow the loss of those who would like to find out more about our past culture and traditions.\n\n\tThe event will unfold as a cozy party to celebrate the end of the year. We will revise the events that took place at Salon Saigon – 6D Ngo Thoi Nhiem, D3. Here, we will not only reflect on our year and meet and greet our scholars and historians, we will also celebrate an early “New year’s Eve” and explore the customs and traditions of our ancestors, then inherit our history and take charge of our future.\n\n\tAbout ĐạiNamHộiQuán Group\n\n\tFounded on December 17th 2007, DaiNam HoiQuan has now consisted of 14 members. This is the heart of common desires to explore and enrich knowledge on past values, and Southernmost and Vietnamese culture. The slow disappearance and derailment of past values is the motivation that strives the founding of DaiNam HoiQuan.\n\n\tThroughout 2019, the group has had a series of projects and programs introducing the traditional marriage, the story of the Ao dai, small talks of past stories, jamming of the past, etc. and now, to celebrate the ending of Ky Hoi year (year of the pig), DaiNam HoiQuan would like to recall our yearlong path and introduce the past Tet of the South, highlight its difference from that of today, and finally connecting all of the culture lovers in a place where we can meet, greet, and share our precious lessons, and our past stories.',
    agency: 'Salon Saigon',
  },
  {
    title: '[CẦN THƠ] Honda Youth Fest  Đại nhạc hội Khinh Khí Cầu',
    link:
      'https://ticketbox.vn/event/hondayouthfestdainhachoikhinhkhicauhcm77941',
    card:
      'https://static.ticketbox.vn/Upload/eventcover/2019/12/16/5A969D.jpg?w=360&maxheight=137&mode=crop&anchor=topcenter',
    coverImg:
      'https://ticketbox.vn/event/hondayouthfestdainhachoikhinhkhicauhcm77941',
    location: 'Can Tho',
    category: 'Nhạc sống',
    tablecell: '',
    datemonth: 'Tháng 12',
    datenum: '22',
    kindOfStage: '',
    dateday: 'Chủ nhật',
    datemonth1: '',
    Headline: '',
    datetime: '',
    locationName: '',
    address: '',
    description: '',
    agency: '',
  },
  {
    title: '[ĐÀ NẴNG] Honda Youth Fest  Đại nhạc hội Khinh Khí Cầu',
    link:
      'https://ticketbox.vn/event/hondayouthfestdainhachoikhinhkhicauhcm77942',
    card:
      'https://static.ticketbox.vn/Upload/eventcover/2019/11/22/2DC34E.jpg?w=360&maxheight=137&mode=crop&anchor=topcenter',
    coverImg:
      'https://ticketbox.vn/event/hondayouthfestdainhachoikhinhkhicauhcm77942',
    location: 'Da Nang',
    category: 'Nhạc sống',
    tablecell: '',
    datemonth: 'Tháng 1',
    datenum: '04',
    kindOfStage: '',
    dateday: 'Thứ 7',
    datemonth1: '',
    Headline: '[ĐÀ NẴNG] Honda Youth Fest  Đại nhạc hội Khinh Khí Cầu',
    datetime: 'Thứ 7, 04 Tháng 1 2020 (07:30 AM  10:00 PM)',
    locationName: 'Quãng Trường 2/9',
    address: 'Hoà Cường, Quận Hải Châu, Thành Phố Đà Nẵng',
    description: 'Honda Youth Fest  Đại nhạc hội Khinh Khí Cầu',
    agency: 'Honda',
  },
  {
    title: '[HÀ NỘI] Honda Youth Fest  Đại nhạc hội Khinh Khí Cầu',
    link:
      'https://ticketbox.vn/event/hondayouthfestdainhachoikhinhkhicauhcm77943',
    card:
      'https://static.ticketbox.vn/Upload/eventcover/2019/11/22/7E2B07.jpg?w=360&maxheight=137&mode=crop&anchor=topcenter',
    coverImg:
      'https://ticketbox.vn/event/hondayouthfestdainhachoikhinhkhicauhcm77943',
    location: 'Ha Noi',
    category: 'Nhạc sống',
    tablecell: '',
    datemonth: 'Tháng 1',
    datenum: '11',
    kindOfStage: '',
    dateday: 'Thứ 7',
    datemonth1: '',
    Headline: '[HÀ NỘI] Honda Youth Fest  Đại nhạc hội Khinh Khí Cầu',
    datetime: 'Thứ 7, 11 Tháng 1 2020 (07:30 AM  10:00 PM)',
    locationName: 'Sân Vận Động Hàng Đẫy',
    address: '9 Trịnh Hoài Đức, Cát Linh, Quận Đống Đa, Thành Phố Hà Nội',
    description: 'Honda Youth Fest  Đại nhạc hội Khinh Khí Cầu',
    agency: 'Honda',
  },
  {
    title: 'Early Photography in Vietnam',
    link: 'https://ticketbox.vn/event/earlyphotographyinvietnam77954',
    card:
      'https://static.ticketbox.vn/Upload/eventcover/2019/11/22/EA9DCB.jpg?w=360&maxheight=137&mode=crop&anchor=topcenter',
    coverImg: 'https://ticketbox.vn/event/earlyphotographyinvietnam77954',
    location: 'Ho Chi Minh',
    category: 'Văn hóa nghệ thuật',
    tablecell: '80.000 VND',
    datemonth: 'Tháng 12',
    datenum: '27',
    kindOfStage: '',
    dateday: 'Thứ 6',
    datemonth1: '',
    Headline: 'Early Photography in Vietnam',
    datetime: 'Thứ 6, 27 Tháng 12 2019 (06:30 PM  08:30 PM)',
    locationName: 'Salon Saigon',
    address: '6D Ngo Thoi Nhiem, Quận 3, Thành Phố Hồ Chí Minh',
    description:
      '"Early Photography in Vietnam" \nA Talk by Terry Bennett\n\nLanguage: English & Vietnamese\n\nTime: Friday, December 27th, 2019 from 6.30pm\n\nTickets:\n\n Through Ticketbox.vn: 130,000vnd / Normal Ticket ( 80,000vnd / student & Salon Saigon Member tkt)\n\n At Entrance:                 150,000vnd / Normal tkt (100,000vnd / student & Salon Saigon Member tkt)\n\n** Vietnam\'s economic growth rate in recent years has been impressive. If it continues on its current trajectory, within a few short years, it is likely to become one of the major economies in Asia. The country has had a turbulent history – not least throughout the nineteenth and most of the twentieth centuries. Under French control for 100 years from the 1850s until the 1950s, this book captures that period on camera. Early Photography in Vietnam chronicles the advent of photography in Vietnam, and then, through the lense of the photographer – either Vietnamese or foreign  allows the reader to witness the events which affected and shaped its destiny.\n\nBritish writer and photohistorian, Terry Bennett, will discuss his latest book, Early Photography in Vietnam, which is the first comprehensive publication on the history of photography in Vietnam. The book also tells the story of the development of photography during the French colonial period from the 1850s until independence in the 1950s.\n\nDuring his talk, Bennett will discuss the introduction of the camera to Vietnam, the development of French and Vietnameseowned studios, and the lives of some of the main photographers. His talk will be illustrated with rare photographs – many of which have not been previously published. These will include the first ever photograph taken in Vietnam in 1845; the earliest photographs of Vietnam and the Vietnamese (1850s1860s); portraits of royalty, mandarins, merchants, shopkeepers, farmworkers; different ethnic groups; early views of Saigon, Hue, Hanoi etc.; 1863 embassy to France; the independence struggle up to the 1950s.',
    agency: 'Salon Saigon',
  },
  {
    title: 'Triển lãm trên màn ảnh rộng : Tôi, Claude Monet',
    link: 'https://ticketbox.vn/event/claudemonet77957',
    card:
      'https://static.ticketbox.vn/Upload/eventcover/2019/11/27/4FA2EE.jpg?w=360&maxheight=137&mode=crop&anchor=topcenter',
    coverImg: 'https://ticketbox.vn/event/claudemonet77957',
    location: 'Ha Noi',
    category: 'Văn hóa nghệ thuật',
    tablecell: '100.000 VND',
    datemonth: 'Tháng 1',
    datenum: '03',
    kindOfStage: 'Sân khấu',
    dateday: 'Thứ 6',
    datemonth1: '',
    Headline: 'Triển lãm trên màn ảnh rộng : Tôi, Claude Monet',
    datetime: 'Thứ 6, 03 Tháng 1 2020 (07:00 PM  09:00 PM)',
    locationName: "Trung tâm Văn hóa Pháp tại Hà Nội  L'Espace",
    address: '24 Tràng Tiền, Quận Hoàn Kiếm, Thành Phố Hà Nội',
    description:
      "(En français plus bas)\n\nTriển lãm trên màn ảnh rộng\n\n \nBUỔI CHIẾU ĐẶC BIỆT!!!\n\nTôi, Claude Monet\n\nĐạo diễn : Phil GRABSKY\n\n \n\n19h00 : Trường phái ấn tượng và đại diện danh tiếng nhất  Claude Monet qua phần giới thiệu của hoạ sĩ, nhà giáo dục nghệ thuật Vu Do. Tốt nghiệp Viện Hàn Lâm Mỹ Thuật Pennsylvania của Mỹ (PAFA), Vu Do là người sáng lập The Painter's Studio.\n\n19h30 : Chiếu phim \n\nTôi, Claude Monet vén mở một cuộc sống nội tâm đầy biến động với những khoảnh khắc tiêu trầm cực độ và cả những thăng hoa sáng tạo đầy mỹ diệu, mang lại cho khán giả một bức chân dung nhiều chiều về một trong những họa sĩ nổi tiếng và có ảnh hưởng sâu sắc nhất đến nền hội hoạ thế giới giai đoạn từ thế kỉ XIX đến cuối thế kỉ XX. Hơn một trăm bức tranh với định dạng chất lượng cao cũng sẽ được giới thiệu trên màn ảnh rộng đem tới một góc nhìn độc nhất về sự nghiệp sáng tạo đồ sộ của danh họa người Pháp.\n\n \n\n\n\nExposition au cinéma\n\nPROJECTION SUPPLEMENTAIRE!!!\n\nMoi, Claude Monet\n\nMise en scène : Phil GRABSKY\n\n \n\n19h00 : L’impressionnisme et son représentant le plus illustre  Claude Monet, présenté par l'artiste et enseignant Vu Do. Diplômé de l’Académie artistique de Pennsylvanie aux EtatsUnis (PAFA), Vu Do est fondateur de Painter’s Studio.\n\n19h30 : Projection du film\n\nMoi, Claude Monet révèle une vie intérieure tumultueuse marquée par des moments de dépression intense et de création euphorique, offrant un portrait complexe de l’un des artistes les plus appréciés au monde. Moi, Claude Monet présente également plus d’une centaine de tableaux de Monet filmés en haute définition, offrant une fenêtre unique sur sa vie émotionnelle et créative.",
    agency: "TRUNG TÂM VĂN HÓA PHÁP TẠI HÀ NỘIL'ESPACE",
  },
  {
    title: 'Pop  rock : The Rodeo',
    link: 'https://ticketbox.vn/event/canhacphaptherodeo77958',
    card:
      'https://static.ticketbox.vn/Upload/eventcover/2019/11/27/B7AFA3.jpg?w=360&maxheight=137&mode=crop&anchor=topcenter',
    coverImg: 'https://ticketbox.vn/event/canhacphaptherodeo77958',
    location: 'Ha Noi',
    category: 'Nhạc sống',
    tablecell: '100.000 VND',
    datemonth: 'Tháng 2',
    datenum: '21',
    kindOfStage: 'Văn hóa nghệ thuật',
    dateday: 'Thứ 6',
    datemonth1: '',
    Headline: 'Pop  rock : The Rodeo',
    datetime: 'Thứ 6, 21 Tháng 2 2020 (08:00 PM  09:30 PM)',
    locationName: "Trung tâm Văn hóa Pháp  L'Espace",
    address: '24 Tràng Tiền., Quận Hoàn Kiếm, Thành Phố Hà Nội',
    description:
      "Pop  rock : The Rodeo \n\nHội trường Trung tâm văn hóa Pháp  L'Espace, 24 Tràng Tiền, Hà Nội. \n\n \n\nThe Rodeo là nghệ danh của nhạc sĩ, ca sỹ người Pháp gốc Việt Dorothée Hannequin (tên Dorothée đảo ngược thành The Rodeo). Nữ nghệ sĩ đa tài này cũng được biết đến như là một nữ diễn viên, nhà thiết kế phục trang và sản xuất phim. Nhóm nhạc The Rodeo sẽ biểu diễn lần đầu tiên tại sân khấu L’Espace. Nữ ca sỹ Dorothée chắc chắn sẽ làm mê hoặc công chúng thủ đô bởi giọng hát mượt mà cùng những giai điệu ngọt ngào đượm chút u sầu. Một đêm nhạc pop pha vị rock hoang dã không nên bỏ lỡ !\n\nNghệ sĩ :\n\nMathieu Geghre : Đàn phím \n\nJérôme Laperruque : Guitar bass \n\nGaëtan Allard : Trống \n\nDorothée Hannequin : Hát & guitar\n\n\n\nThe Rodeo est l’anagramme du prénom de Dorothée Hannequin, musicienne et chanteuse française d’origine vietnamienne qui mène ce groupe pop/rock. Cette artiste talentueuse est également connue comme actrice, costumière et productrice de film. The Rodeo se produit sur la scène de L’Espace pour la première fois. Dorothée saura séduire le public hanoien par sa voix de velours et des mélodies sucrées mais aussi mélancoliques. Une soirée musicale plus pop que rock, mais toujours un peu sauvage à ne pas rater.\n\nArtistes : \n\nMathieu Geghre: Claviers\n\nJérôme Laperruque : Basse\n\nGaëtan Allard : Batterie\n\nDorothée Hannequin : Chant & guitare",
    agency: "TRUNG TÂM VĂN HÓA PHÁP TẠI HÀ NỘIL'ESPACE",
  },
  {
    title: 'Độc tấu piano : Maxime Zecchini',
    link: 'https://ticketbox.vn/event/doctaupianomaximezucchini77959',
    card:
      'https://static.ticketbox.vn/Upload/eventcover/2019/12/09/D7253C.jpg?w=360&maxheight=137&mode=crop&anchor=topcenter',
    coverImg: 'https://ticketbox.vn/event/doctaupianomaximezucchini77959',
    location: 'Ha Noi',
    category: 'Nhạc sống',
    tablecell: '100.000 VND',
    datemonth: 'Tháng 2',
    datenum: '29',
    kindOfStage: 'Văn hóa nghệ thuật',
    dateday: 'Thứ 7',
    datemonth1: '',
    Headline: 'Độc tấu piano : Maxime Zecchini',
    datetime: 'Thứ 7, 29 Tháng 2 2020 (08:00 PM  09:30 PM)',
    locationName: "Trung tâm văn hóa Pháp  L'Espace",
    address: '24 Tràng Tiền, Quận Hoàn Kiếm, Thành Phố Hà Nội',
    description:
      "(En français plus bas)\n\nĐộc tấu piano : Maxime Zecchini\n\nVới các tác phẩm kinh điển của Debussy, Ravel, Fauré và các nhà soạn nhạc người Pháp khác.\n\n \n\nNgay từ đầu, ta đã bị mê hoặc bởi sự điêu luyện của bàn tay trái, khiến ta tưởng như đang nghe mười ngón tay lướt trên phím đàn với tốc độ cực nhanh, từ cực trầm đến cực cao, nhân lên những lớp lang âm thanh và tiếp nối với những quãng kịch tính một cách nhẹ nhàng, thanh thoát. (Sarah Léon, tạp chí âm nhạc Classica)\n\n \n\nLà chủ nhân của nhiều giải thưởng quốc gia, quốc tế, nghệ sĩ dương cầm Maxime Zecchini không chỉ khiến người nghe sửng sốt bởi kỹ thuật điêu luyện mà còn bởi lựa chọn táo bạo : tôn vinh những tác phẩm chơi bằng tay trái. Nghệ sĩ đã lưu diễn khắp bốn mươi quốc gia, và đĩa nhạc của anh  tuyển tập các tác phẩm dành cho tay trái (đĩa nhạc đầu tiên trong lịch sử ngành xuất bản đĩa thu âm chỉ gồm các bản thu dành cho tay trái) được nhà xuất bản danh tiếng Ad Vitam Records & Harmonia Mundi phát hành trên toàn thế giới.\n\n \n\nChương trình \n\nClaude Debussy (1862 – 1918) \n\n Ba khúc dạo đầu (hai tay  12’)\n\n \n\nCharlesValentin Alkan (1813 – 1888) \n\n Bản fantasy, opus 76 (tay trái  10’)\n\n \n\nClaude Debussy (1862 – 1918) \n\n Ánh trăng (hai tay  5’)\n\n \n\nPierre Sancan (1916 – 2008) \n\n Caprice Romantique (tay trái  6’)\n\n \n\nGabriel Fauré (1845 – 1924) \n\n Bản tình ca không lời, opus 17 n°3 (hai tay  4')\n\n \n\nMaurice Ravel (1875 – 1937) \n\n Khúc dạo đầu (hai tay  2' )\n\n \n\nMaurice Ravel (1875 – 1937) \n\n Bản concerto cho tay trái (tay trái  10')\n\n \n\nMichel Legrand (1932 – 2019) \n\n Bộ tác phẩm soạn cho bộ phim Những chiếc ô thành Cherbourg (hai tay – 10’)\n\n \n\nNhiều tác giả \n\n Chùm ca khúc Pháp nổi tiếng (hai tay – 5’)\n\n\n\n \n\nRécital de piano : Maxime Zecchini\n\nAvec des chefsd'œuvre de Debussy, Ravel, Fauré et d'autres compositeurs français.\n\n \n\nD'emblée, on est fasciné par la virtuosité de cette fameuse main gauche, qui donne l'illusion d'avoir dix doigts, se déplace à une allure vertigineuse de l'extrême grave à l'extrême aigu, multiplie les plans sonores et enchaîne avec aisance des traits perilleux. (Sarah Léon, magazine Classica)\n\n \n\nLauréat de plusieurs fondations et concours, nationaux et internationaux, le pianiste Maxime Zecchini étonne autant par la virtuosité de son jeu que par sa démarche audacieuse : remettre à l’honneur le répertoire de la main gauche. Il s'est produit en concert dans une quarantaine de pays, et sa discographie – une Anthologie des œuvres pour la main gauche (une première dans l’édition phonographique) publiée par Ad Vitam Records & Harmonia Mundi  est distribuée dans le monde entier.\n\n \n\nProgramme : \n\nClaude Debussy (1862 – 1918) \n\n Trois Préludes (deux mains  12')\n\n \n\nCharlesValentin Alkan (1813 – 1888)\n\n Fantaisie opus 76 (main gauche  10')\n\n \n\nClaude Debussy (1862 – 1918) \n\n Clair de Lune (deux mains  5')\n\n \n\nPierre Sancan (1916 – 2008)\n\n Caprice Romantique (main gauche  6')\n\n \n\nGabriel Fauré (1845 – 1924) \n\n Romance sans paroles opus 17 n°3 (deux mains  4')\n\n \n\nMaurice Ravel (1875 – 1937) \n\n Prélude (deux mains  2')\n\n \n\nMaurice Ravel (1875 – 1937) \n\n Concerto pour la main gauche (main gauche  10')\n\n \n\nMichel Legrand (1932 – 2019) \n\n Suite sur les Parapluies de Cherbourg (deux mains  10')\n\n \n\nDivers compositeurs \n\n Suite de très célèbres chansons françaises (deux mains  5')",
    agency: "TRUNG TÂM VĂN HÓA PHÁP TẠI HÀ NỘIL'ESPACE",
  },
  {
    title: 'Rock Symphony Concert',
    link: 'https://ticketbox.vn/event/rocksymphonyconcert78005',
    card:
      'https://static.ticketbox.vn/Upload/eventcover/2019/11/25/B4D4DE.jpg?w=360&maxheight=137&mode=crop&anchor=topcenter',
    coverImg: 'https://ticketbox.vn/event/rocksymphonyconcert78005',
    location: 'Ho Chi Minh',
    category: 'Văn hóa nghệ thuật',
    tablecell: '450.000 VND',
    datemonth: '',
    datenum: '',
    kindOfStage: 'Sân khấu',
    dateday: '',
    datemonth1: 'Tháng 12',
    Headline: '',
    datetime: '',
    locationName: '',
    address: '',
    description: '',
    agency: '',
  },
  {
    title: 'Sài Gòn  Chợ Lớn Urban Landscape Design Then & Now',
    link:
      'https://ticketbox.vn/event/saigoncholonurbanlandscapedesignthennow78022',
    card:
      'https://static.ticketbox.vn/Upload/eventcover/2019/11/30/1316EC.jpg?w=360&maxheight=137&mode=crop&anchor=topcenter',
    coverImg:
      'https://ticketbox.vn/event/saigoncholonurbanlandscapedesignthennow78022',
    location: 'Ho Chi Minh',
    category: 'Hội thảo',
    tablecell: '80.000 VND',
    datemonth: 'Tháng 12',
    datenum: '20',
    kindOfStage: 'Văn hóa nghệ thuật',
    dateday: 'Today',
    datemonth1: '',
    Headline: 'Sài Gòn  Chợ Lớn Urban Landscape Design Then & Now',
    datetime: 'Thứ 6, 20 Tháng 12 2019 (06:30 PM  08:30 PM)',
    locationName: 'Salon Saigon',
    address: '6D Ngo Thoi Nhiem, Quận 3, Thành Phố Hồ Chí Minh',
    description:
      '** PLEASE SCROLL DOWN FOR ENGLISH**\n\n\tKiến trúc đô thị cảnh quan SaigonChợ Lớn xưa và nay qua hình ảnh và tranh \n\n\tBuổi trình bày của diễn giả Nguyễn Đức Hiệp\n\n\tNgôn ngữ: Tiếng Việt & Tiếng Anh\n\n\tThời gian: Thứ Sáu, 20/12/2019 từ 18h30\n\n\tGiá vé: \n\n\t Trên trang Ticketbox.vn: 150,000 vnd / vé thường (80,000 vnd / vé sinh viên và thành viên Salon Saigon)\n\n\t Tại cửa vào Salon:          170,000vnd / vé thường (100,000 vnd / vé sinh viên và thành viên Salon Saigon)\n\n\t \n\n\t** Thành phố Hồ Chí Minh mà trước đó được gọi là Sàigòn, dưới thời Pháp thuộc là thủ phủ của Nam kỳ lục tỉnh đã được luật sư Jules Blancsubé (18341888)  thị trưởng SàiGòn, có thời gian làm đại biểu Nam kỳ ở quốc hội Pháp, người đầu tiên tuyên bố  trong nhiều dịp khi nói vê thành phố SàiGòn mà ông sinh sống từ năm 1864 là "La Perle de l’ExtrêmeOrient” (Hòn ngọc Viễn Đông). Từ đó thành phố Hòn ngọc Viễn Đông này đã cám dỗ nhiều nhà du hành vào cuối thế kỷ 19 đến đầu thế kỷ 20 đến thăm, mà ngay cả những người Anh khi ghé qua SàiGòn từ Hồng Kông hay Singapore đều ghi trong ký sự và sách du hành là thành phố thiết kế với cảnh quan đẹp và kiến trúc ÁÂu đẹp hơn so với hai thành phố Singapore và Hồng Kông.\n\n\tTrong buổi nói chuyện, diễn giả sẽ trình bày các hình ảnh và câu chuyện lịch sử văn hóa, sinh hoạt xã hội về các con đường, các tòa nhà và cảnh quan xưa và nay từ Quận 1 (chợ Bến Thành, phường Bến Nghé, đường Trần Hưng Đạo) đến Quận 5 (Hải Thượng Lãn Ông, Phùng Hưng, Trịnh Hoài Đức, Nguyễn Thi, Triệu Quang Phục, Nguyễn Trãi,...).   Bề dày lịch sử văn hóa và di sản kiến trúc của thành phố SàiGòn và Chợ Lớn cũng không thua kém hai thành phố Singapore và HongKong trong vùng.\n\n\t\n\n\tSài Gòn  Chợ Lớn Urban Landscape Design Then & Now\n\n\tA presentation by Nguyen Duc Huy\n\n\tLanguage: Vietnamese & English\n\n\tTime: Friday, December 20th, 2019 from 6.30pm\n\n\tTickets: \n\n\t Through Ticketbox.vn: 150,000vnd / normal tkt (80,000 vnd / student and Salon Saigon Member tkt)\n\n\t At entrance:                 170,000vnd / normal tkt (100,000 vnd / student and Salon Saigon Member tkt)\n\n\t** Ho Chi Minh City, formerly known as Saigon, during the French colonial period was the capital of Six Provinces of Southern Vietnam. It was also declared many times as "La Perle de l\'ExtrêmeOrient" by lawyer Jules Blancsubé (18341888), the mayor of Saigon, when he came to France as president of the colonial council of Cochinchine. Since then, from the late 19th to early 20th century, "La Perle de l\'ExtrêmeOrient" city attracted not only lots of travelers, but also the British when visiting Saigon from Hong Kong or Singapore. As noted in the memo and travel books, the city is designed with beautiful scenery and beautiful Eurasian architecture compared to Singapore and Hong Kong.\n\n\tThe talk will present historical and cultural images and stories about old and new roads, buildings and landscapes from District 1 (Ben Thanh Market, Ben Nghe Ward, Tran Hung Street Dao) to District 5 (Hai Thuong Lan Ong, Phung Hung, Trinh Hoai Duc, Nguyen Thi, Trieu Quang Phuc, Nguyen Trai, ...). The rich history of cultural and architectural heritage of Sàigon and Cholon cities is not inferior to the two cities of Singapore and Hong Kong in the region.',
    agency: 'Salon Saigon',
  },
  {
    title: 'Trance Session 13: Fables',
    link: 'https://ticketbox.vn/event/trancesession13fables78035',
    card:
      'https://static.ticketbox.vn/Upload/eventcover/2019/11/29/00DBD6.jpg?w=360&maxheight=137&mode=crop&anchor=topcenter',
    coverImg: 'https://ticketbox.vn/event/trancesession13fables78035',
    location: 'Ha Noi',
    category: 'Nhạc sống',
    tablecell: '750.000 VND',
    datemonth: 'Tháng 12',
    datenum: '20',
    kindOfStage: 'Nightlife',
    dateday: 'Today',
    datemonth1: '',
    Headline: 'Trance Session 13: Fables',
    datetime: 'Thứ 6, 20 Tháng 12 2019 (09:00 PM  Đến Tối muộn)',
    locationName: 'The IP Club',
    address:
      'Tầng 6, số 41 Hai Bà Trưng, phường Trần Hưng Đạo, Quận Hoàn Kiếm, Thành Phố Hà Nội',
    description:
      '𝐓𝐑𝐀𝐍𝐂𝐄 𝐒𝐄𝐒𝐒𝐈𝐎𝐍 𝟏𝟑: 𝐅𝐀𝐁𝐋𝐄𝐒\n\n\t⚡️𝐅𝐄𝐑𝐑𝐘 𝐓𝐀𝐘𝐋𝐄 & 𝐃𝐀𝐍 𝐒𝐓𝐎𝐍𝐄⚡️\n\n\t⚡️𝑭𝑹𝑰𝑫𝑨𝒀  𝟐𝟎/𝟏𝟐/𝟐𝟎𝟏𝟗 ⚡️\n\n\t\n\n\t Hai DJ Đặc biệt sẽ xuất hiện tại Trance Session 13  Số cuối năm 2019: FERRY TAYLE & DAN STONE sẽ chơi một set B2B 5 tiếng đồng hồ đỉnh cao tại chính thánh đường nhạc Trance  IP CLUB.\n\n\t FERRY TAYLE là DJ Trance số 1 nước Pháp và DAN STONE đến từ Vương quốc Anh, cùng mang màu sắc âm nhạc hiện đại, giàu năng lượng và là hai cái tên quen thuộc tại Tomorrowland, Trance Energy, A State Of Trance, Luminosity Events...\n\n\tHẹn gặp lại tất cả các bạn vào ngày 20/12, chúng ta hãy cùng nhau tạo ra một đêm hội thực sự cùng với thương hiệu FABLES đẳng cấp thế giới\n\n\t\n\n\t#IPclubHanoi #IPnightclub\n\n\tAnyone Can Party!',
    agency: 'IP Club Hanoi',
  },
  {
    title: 'Concert: "HOLY NIGHT" by Saigon  Classical',
    link: 'https://ticketbox.vn/event/concertholynightbysaigonclassical78081',
    card:
      'https://static.ticketbox.vn/Upload/eventcover/2019/11/30/792380.jpg?w=360&maxheight=137&mode=crop&anchor=topcenter',
    coverImg:
      'https://ticketbox.vn/event/concertholynightbysaigonclassical78081',
    location: 'Ho Chi Minh',
    category: 'Văn hóa nghệ thuật',
    tablecell: '200.000 VND',
    datemonth: 'Tháng 12',
    datenum: '21',
    kindOfStage: 'Sân khấu',
    dateday: 'Thứ 7',
    datemonth1: '',
    Headline: 'Concert: "HOLY NIGHT" by Saigon  Classical',
    datetime: 'Thứ 7, 21 Tháng 12 2019 (06:30 PM  08:30 PM)',
    locationName: 'Salon Saigon',
    address: '6D Ngo Thoi Nhiem, Quận 3, Thành Phố Hồ Chí Minh',
    description:
      '"HOLY NIGHT"\n\nMột chương trình hoà nhạc cổ điển với sự đóng góp của nhóm Saigon Classical\nA Music Concert curated by Saigon Classical\n\nThứ Bảy, ngày 21/12/2019 từ 18h30\n\nSaturday,  December 21st, 2019, from 6.30pm\n\n \n\nGiá Vé / Tickets:\n\n Đặt trên trang Ticketbox.vn: 450,000vnd (Học sinh / Sinh viên và Thành viên Salon Saigon/ students and members: 200,000vnd)\n\n Tại cửa vào Salon Saigon / at the door: 500,000vnd (đã bán hết vé Sinh viên)\n\n** Salon Saigon và nhóm nhạc Saigon Classical hân hạnh giới thiệu đêm nhạc "HOLY NIGHT”, chương trình hoà nhạc cổ điển đón mừng dịp Giáng Sinh và Year End 2019. Chương trình được thực hiện bởi Saigon Classical, một tổ chức với mong muốn mang những nghệ sĩ biểu diễn nhạc cổ điển Việt Nam đến với công chúng và tạo ra một không gian tận hưởng cho những người yêu âm nhạc cổ điển trong thành phố.\n\n\n** Salon Saigon is delighted to present “HOLY NIGHT”, a unique experience that encompasses classical music and visual arts in an inspiring artistic venue on the occasion of Christmas and Year End 2019. The concert program is curated by Saigon Classical, an organization that aims to bring Vietnamese classical performers to the public and create a platform for classical music lovers in the city.\n\n \n\nPROGRAM\n\n6:30PM: Welcome guest / Đón khách\n\n7:00PM: Performance / Biểu diễn\n\n \n\nPART 1\n\n \n\n \n\nPyotr Ilyich Tchaikovsky: Marche, from Ballet "The Nutcracker", Op.71, Act I\n\nPiano: Trần Thụy San\n\n \n\nPyotr Ilyich Tchaikovsky: Tea (Chinese Dance), from Ballet "The Nutcracker", Op.71, Act II\n\nPiano: Trần Thụy San\n\n \n\nFranz Schubert: "Ave Maria", D.839, Op.52, No.6\n\nSoprano: Huỳnh Hà Thu Thảo, Piano Accompanist: Đặng Trí Dũng\n\n \n\nWolfgang Amadeus Mozart: Aria "Voi che sapete", from Opera "Le nozze di Figaro"\n\nSoprano: Huỳnh Hà Thu Thảo, Piano Accompanist: Đặng Trí Dũng\n\n \n\nChas.W Storm: Glen Eden Polka (A Concer Polka)\n\nTrumbone: Phan Anh Quân, Piano Accompanist: Trần Thụy San\n\n \n\nFrédéric Chopin: Nocturne in Csharp minor, Op. posth.\n\nPiano: Đặng Trí Dũng\n\n \n\nWolfgang Amadeus Mozart: Aria "Chi sà, chi sà, qual sia", K.582 \n\nSoprano: Huỳnh Hà Thu Thảo, Piano Accompanist: Đặng Trí Dũng\n\n \n\nPART 2\n\nClaude Debussy: "Clair de Lune", from The Suite Bergamasque\n\nPiano: Đặng Trí Dũng\n\n \n\nGabriel Fauré: Rêve d\'amour, Op.5, No.2\n\nTenor: Bùi Thái Hòa, Piano Accompanist: Đặng Trí Dũng\n\n \n\nBob Thiele & George David Weiss: What a Wonderful World \n\nTrumpet: Nguyễn Hoàng Thiên Ân, Piano: Trần Thụy San\n\n \n\nFranz Schubert: "Auf dem Flusse" from song cycle "Winterreise", D. 911 \n\nTenor: Bùi Thái Hòa, Piano Accompanist: Đặng Trí Dũng\n\n \n\nGeorge Frideric Handel: Every valley shall be exalted, from Oratorio "Messiah" \n\nTenor: Bùi Thái Hòa, Piano Accompanist: Đặng Trí Dũng\n\n \n\nChristian hymn, arr. Rich Ridenour: Simple Gifts / Amazing Grace \n\nTrumpet: Nguyễn Hoàng Thiên Ân,Trumbone: Phan Anh Quân, Piano: Trần Thụy San\n\n \n\n***** ***** *****\n\nMột số lưu ý / Notice:\n\n Không dẫn theo trẻ em dưới 6 tuổi / Children under 6 are not allowed\n Chụp ảnh không dùng đèn flash / No Flash while taking photos\n Đem theo thẻ sinh viên/học sinh hợp lệ để check in đối với vé sinh viên/học sinh.',
    agency: 'Salon Saigon',
  },
  {
    title: 'Chào mừng Mùa Lễ hội  Holiday Celebration',
    link: 'https://ticketbox.vn/event/holidaycelebration78085',
    card:
      'https://static.ticketbox.vn/Upload/eventcover/2019/12/02/9902BF.jpg?w=360&maxheight=137&mode=crop&anchor=topcenter',
    coverImg: 'https://ticketbox.vn/event/holidaycelebration78085',
    location: 'Ha Noi',
    category: 'Văn hóa nghệ thuật',
    tablecell: '300.000 VND',
    datemonth: 'Tháng 12',
    datenum: '20',
    kindOfStage: 'Sân khấu',
    dateday: 'Today',
    datemonth1: '',
    Headline: 'Chào mừng Mùa Lễ hội  Holiday Celebration',
    datetime: 'Thứ 6, 20 Tháng 12 2019 (08:00 PM  10:30 PM)',
    locationName:
      'Học viện Âm nhạc Quốc gia Việt Nam / Vietnam National Academy of Music',
    address: '77 Hào Nam, Quận Đống Đa, Thành Phố Hà Nội',
    description:
      'Hãy cùng đắm mình trong không gian Giáng sinh cùng những người thân yêu qua những giai điệu âm nhạc ấm áp thể hiện bởi Dàn nhạc Giao hưởng Mặt Trời.\n\n\t\n\n\tCome celebrate the holiday season with Sun Symphony Orchestra who will be performing familiar songs that the whole family will enjoy. Tap your toes, clap your hands and sing along to these cherished favorites.',
    agency: 'Sun Symphony Orchestra (SSO)',
  },
  {
    title: 'Liveshow Cảm Ơn Người Tình  Bóng Hồng Trong Tình Ca Lam Phương',
    link:
      'https://ticketbox.vn/event/liveshowcamonnguoitinhbonghongtrongtinhcalamphuong78131',
    card:
      'https://static.ticketbox.vn/Upload/eventcover/2019/12/05/EB0393.jpg?w=360&maxheight=137&mode=crop&anchor=topcenter',
    coverImg:
      'https://ticketbox.vn/event/liveshowcamonnguoitinhbonghongtrongtinhcalamphuong78131',
    location: 'Lam Dong',
    category: 'Văn hóa nghệ thuật',
    tablecell: '600.000 VND',
    datemonth: 'Tháng 12',
    datenum: '28',
    kindOfStage: 'Sân khấu',
    dateday: 'Thứ 7',
    datemonth1: '',
    Headline: 'Liveshow Cảm Ơn Người Tình  Bóng Hồng Trong Tình Ca Lam Phương',
    datetime: 'Thứ 7, 28 Tháng 12 2019 (07:30 PM  11:30 PM)',
    locationName: 'Dalat Edensee Resort',
    address:
      'Khu chức năng VII.2 – Khu du lịch hồ Tuyền Lâm, Thành Phố Đà Lạt, Tỉnh Lâm Đồng',
    description:
      'Đêm nhạc đặc biệt kỷ niệm 70 năm âm nhạc Lam Phương với chủ đề CẢM ƠN NGƯỜI TÌNH – BÓNG HỒNG TRONG TÌNH CA LAM PHƯƠNG được diễn ra vào lúc 19 giờ 30 phút ngày 28122019, tại Dalat Edensee Resort (Khu Du lịch hồ Tuyền Lâm, Đà Lạt). Đây là show nhạc được dàn dựng sang trọng, lịch lãm và bay bổng với sự góp mặt của các giọng ca, tên tuổi từng gắn bó với dòng nhạc Lam Phương: Elvis Phương, Họa Mi, Hà Vân, Hoàng Lê Vi, Nam Cường.\n\t\n\tCùng với việc phát hành cuốn tiểu sử, chân dung LAM PHƯƠNG – TRĂM NHỚ NGÀN THƯƠNG (Nguyễn Thanh Nhã chấp bút, Phanbook & NXB Phụ Nữ, 2019) đang gây chú ý trong dư luận, đêm nhạc đặc biệt này chính là món quà ý nghĩa thay cho lời tri ân mà ban tổ chức gửi đến người nhạc sĩ tài hoa bậc nhất của nền tân nhạc Việt Nam. Và đây cũng là món ăn tinh thần đầy ý nghĩa trong mùa lễ hội cuối năm tại thành phố Đà Lạt.\n\t\n\tLam Phương, tác giả của “gia tài” 217 ca khúc nổi tiếng. Ông đã có một sự gắn bó đặc biệt với “thành phố  giai nhân” Đà Lạt. Từ trước năm 1975, Lam Phương đã đưa thành phố thơ mộng này đi vào những ca khúc đẹp, làm say lòng khán giả, có thể kể đến: Thành phố buồn và Đà Lạt cô liêu. \n\t\n\tTrong cuộc đời nhiều thăng trầm và hào hoa, những người tình trong đời thực đã thấp thoáng phía sau các ca khúc nổi tiếng của Lam Phương. Lần này, câu chuyện về người nghệ sĩ hào hoa với những bóng hồng, giai nhân một thuở sẽ được tái hiện cùng những ca khúc kinh điển, gắn bó với ký ức của nhiều người.\n\t\n\tKhán giả ái mộ nhạc sĩ Lam Phương sẽ được thưởng thức những bản tình ca bất hủ của ông trong không gian lãng mạn, khói sương và đầy ắp hoài niệm: Thành phố buồn, Kiếp nghèo, Cho em quên tuổi ngọc, Em đi rồi, Một mình…\n\t\n\tChương trình do Công Ty TNHH Phan Lệ & Friends tổ chức.\n\t\n\tTHÔNG TIN VÉ:\n\tCác mức giá:\n\tVé A: 1,000,000 VNĐ\n\tVé B: 800,000 VNĐ\n\tVé C: 600,000 VNĐ',
    agency: 'Thương hiệu sách Phanbook  Công ty TNHH Phan Lệ & Friends',
  },
];
